theme = "docs-balsamiq-com"
baseurl = "http://docs.balsamiq.com/"
languageCode = "en-us"
title = "Balsamiq Documentation"
MetaDataFormat = "toml"
pluralizeListTitles = false
Paginate = "50"
PageSize = "50"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
SectionPagesMenu = "main"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Docs"
  identifier = "docs"
  url = "/docs/"

[[menu.main]]
  name = "FAQs"
  identifier = "faqs"
  url = "/faqs/"

[[menu.main]]
  name = "Resources"
  identifier = "resources"
  url = "/resources/"

[blackfriday]
  plainIdAnchors = true
