theme = "balsamiq"
baseurl = "http://docs.balsamiq.com/"
languageCode = "en-us"
title = "Balsamiq Documentation"
MetaDataFormat = "toml"
pluralizeListTitles = false
Paginate = "10"
PageSize = "10"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
SectionPagesMenu = "main"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Docs"
  url = "/docs/"

[[menu.main]]
  name = "FAQs"
  url = "/faqs/"

[[menu.main]]
  name = "Resources"
  url = "/resources/"

  [blackfriday]
plainIdAnchors = true
